# Bài giảng về Đại số tuyến tính
## MaSSP 2017, Computer Science
__Chuẩn bị: Nguyễn Vương Linh__

__Chỉnh sửa: Vũ Minh Châu__

Bài giảng sau đây giới thiệu một số kiến thức cơ bản về đại số tuyến tính cần thiết để hiểu và thực hiện chương trình <b>Deep Learning</b>.

Bài giảng này bỏ qua một số kiến thức quan trọng (ví dụ như vector riêng - eigen vector), và không đi sâu vào phân tích tính chất của các khái niệm.

Đối tượng cơ bản trong đại số tuyến tính là __ma trận__ và __vector__. 

Ví dụ cơ bản sau đây giới thiệu cách thức tương tác với ma trận trong numpy và được thực hiện với __ma trận 2 chiều__, tuy nhiên các phép toán cơ bản là không thay đổi nếu với số chiều khác.

Bài giảng này sử dụng thư viện <b>numpy</b> trong Python để thực hiện các ví dụ minh hoạ.

Numpy là một trong những thư viện mã nguồn mở nổi tiếng nhất của Python và được sử dụng rộng rãi trong nhiều chương trình <b>Machine Learning</b> nói chung và <b>Deep Learning</b> nói riêng.

Mục tiêu chính của numpy là tối ưu và đơn giản hoá các phép toán liên quan đến đại số tuyến tính. Trước khi bắt đầu, hãy cài đặt numpy, và bắt đầu chương trình Python (hoặc notebook) bằng lệnh sau:

In [ ]:
import numpy as np

Lưu ý: khi bạn tải lại notebook này, bạn phải chạy lại lệnh import nói trên.

# 0. Khởi tạo ma trận và vector
Chúng ta bắt đầu với việc khởi tạo một ma trận A và in ra các thông tin cơ bản của A.

Ma trận A có kích thước 2 x 5, các phần tử từ 0 đến 9, theo thứ tự tăng dần từ trái qua phải và từ trên xuống.

$$ A = 
    \begin{bmatrix}
        0 & 1 & 2 & 3 & 4 \\
        5 & 6 & 7 & 8 & 9
    \end{bmatrix}
$$

Để khởi tạo 1 ma trận với các phần tử được biết trước, sử dụng $np.array$ và nhóm các phần tử trong cùng một hàng vào một list, và nhóm các hàng vào thành một list lớn hơn.

In [ ]:
A = np.array([[0, 1, 2, 3, 4],
              [5, 6, 7, 8, 9]])
print(A)

Hãy thử khởi tạo ma trận sau đây:
$$ A2 = 
    \begin{bmatrix}
        3 & 4 \\
        5 & 6 \\
        7 & 8
    \end{bmatrix}
$$

In [ ]:
# code


_Lưu ý:_ Luôn luôn phải có $[\ ]$ để xác định các phần tử trong ma trận.

Ví dụ sau đây là <span style="color: red">SAI</span>. Hãy chạy cell này và quan sát lỗi nhận được

In [ ]:
B1 = np.array(1,2,3,4)

Quay lại với ma trận $A$ có kích thước 2x5 ban đầu, ta sẽ in các thông tin cơ bản của $A$.

Trước hết, $A.shape$ sẽ cho thông tin về kích thước của ma trận.

In [ ]:
""" A
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]]
"""
print("Shape: {}".format(A.shape))      # In thông tin về kích thước của A

Kết quả thu được là một $tuple$. Để truy cập thông tin của A theo từng chiều, ta sử dụng chỉ số với $A.shape$.

In [ ]:
""" A
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]]
"""
print(A.shape[0])  
print(A.shape[1])

Ngoài ra, $A.ndim$ sẽ cho biết số chiều của ma trận, và $A.size$ cho biết số phần tử có trong A.

In [ ]:
""" A
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]]
"""
print("Dimension: {}".format(A.ndim))   # In số chiều của A

print("Size: {}".format(A.size))        # In số phần tử có trong A

$np.array$ tự động xác định kiểu dữ liệu của ma trận khi khởi tạo. Hãy in thông tin từ $A.dtype$ để biết kiểu dữ liệu hiện tại của các phần tử trong A.

In [ ]:
# code


Tuy vậy ta có thể sử dụng __dtype__ để ép kiểu dữ liệu trong ma trận khi khởi tạo. Ví dụ nếu muốn khởi tạo ma trận $A2$ sao cho các phần tử của $A2$ có kiểu số thực, ta làm như sau:

In [ ]:
A2 = np.array([[3, 4], [5, 6]], dtype=float)  # Sử dụng kiểu số thực

print(A2)
""" Kết quả:
[[ 3.  4.]
 [ 5.  6.]]
"""

print(A2.dtype)  # Kết quả: float64

__Checkpoint 1__: Cho vector $b$, bạn hãy in ra các thông tin của $b$ tương tự như đã làm với ma trận $A$.
$$ b = (6.0, 7.0, 8.0, 9.0, 10.0) $$

In [ ]:
# Khởi tạo b
b = np.array([6., 7., 8., 9., 10.])
# In thông tin về kích thước

# số chiều

# kiểu dữ liệu

# số phần tử


# 1. Các ma trận đặc biệt

* Nếu cần khởi tạo ma trận toàn 0, sử dụng __np.zeros__, kèm theo thông tin về kích thước ma trận

In [ ]:
A3 = np.zeros((6, 5), dtype=int)
print(A3)

""" Kết quả:
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
"""

* Tương tự như thế, bạn có thể khởi tạo ma trận toàn 1 bằng __np.ones__:

In [ ]:
A4 = np.ones((4, 2))
print(A4)
""" Kết quả:
[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
"""

* Ma trận đơn vị được khởi tạo bằng __np.eye__.

$$ A5 = 
    \begin{bmatrix}
        1 & 0 & 0 \\
        0 & 1 & 0 \\
        0 & 0 & 1
    \end{bmatrix}
$$

_Lưu ý ma trận đơn vị chỉ có 2 chiều và luôn là ma trận vuông._

In [ ]:
A5 = np.eye(3)
print(A5)

* Cuối cùng, __np.arange__ tạo ra vector với các phần tử liên tiếp nhau.

    __reshape__ được sử dụng để thay đổi kích thước ma trận hoặc vector.
    
    Kết hợp 2 hàm này ta sẽ thu được một ma trận với các phần tử liên tiếp từ trái qua phải, trên xuống dưới.

In [ ]:
A6 = np.arange(10, 20).reshape(2, 5)
print(A6)

""" Kết quả:
[[10 11 12 13 14]
 [15 16 17 18 19]]
"""

# 2. Truy cập và thay đổi phần tử trong ma trận

Mặc dù hầu hết các phép toán trong Deep Learning không cần truy cập từng phần tử của ma trận, bạn cũng nên biết một vài cách thức cơ bản để thao tác với từng phần tử trong ma trận.

Chúng ta sẽ sử dụng ma trận sau để minh hoạ

$$ A = 
    \begin{bmatrix}
        0 & 1 & 2 & 3 & 4 \\
        5 & 6 & 7 & 8 & 9 \\
        10 & 11 & 12 & 13 & 14 \\
        15 & 16 & 17 & 18 & 19
    \end{bmatrix}
$$

In [ ]:
A = np.arange(20).reshape(4, 5)

Trong numpy (và Python), các phần tử được đánh số từ 0. Numpy cho phép đọc và thay đổi từng phần tử trong ma trận.

Bạn có thể truy cập phần tử bằng $A[i, j]$...

In [ ]:
""" A
[[0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18  19]]
"""
print(A[0, 0])
print(A[3, 4])

... và thay đổi những phần tử này bằng cách gán chúng với một giá trị khác.

In [ ]:
A[0, 0] = 19
A[3, 4] = 0
print(A)
""" Kết quả:
[[19  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18  0]]
"""

# khôi phục lại giá trị ban đầu của ma trận A
A[0, 0] = 0
A[3, 4] = 19

Để truy cập cả một dòng hay một cột, sử dụng dấu 2 chấm __":"__ thay cho chỉ số không cần thiết

$$ A = 
    \begin{bmatrix}
        0 & 1 & 2 & 3 & 4 \\
        5 & 6 & 7 & 8 & 9 \\
        10 & 11 & 12 & 13 & 14 \\
        15 & 16 & 17 & 18 & 19
    \end{bmatrix}
$$

In [ ]:
print(A[0, :])  # In ra dòng đầu tiên. Kết quả: [0 1 2 3 4]
print(A[:, 0])  # In ra cột đầu tiên. Kết quả: [0  5 10 15]

Để truy cập một ma trận con, sử dụng $A[i_1:i_2, j_1:j_2]$ để lấy ra phần chỉ số cần thiết.

_Lưu ý: dùng $i_1:i_2$ để kí hiệu các phần tử từ $i_1$ đến $i_2 - 1$._

$$ A = 
    \begin{bmatrix}
        0 & 1 & 2 & 3 & 4 \\
        5 & 6 & 7 & 8 & 9 \\
        10 & 11 & 12 & 13 & 14 \\
        15 & 16 & 17 & 18 & 19
    \end{bmatrix}
$$

In [ ]:
print(A[2:4, 2:5])
""" Kết quả
[[12 13 14]
 [17 18 19]]
"""

In [ ]:
print(A[0:3, :])
""" Kết quả
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
"""

Ma trận hoặc vector con có thể được gán sang biến khác và truy cập / thay đổi tương ứng.

**CẢNH BÁO**: Python không sao chép ma trận trong phép gán =, cho nên LUÔN LUÔN sử dụng copy để tạo ra một ma trận mới và gán = với ma trận đó.

In [ ]:
# Ví dụ SAI
B1 = A[0:1, 0:3]
B1[0, 0] = -1   # Phép toán này thay đổi giá trị tương ứng trong A
print(B1)
""" Kết quả
[[-1  1  2]]
"""

print(A)
""" Kết quả
[[-1  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
"""

In [ ]:
# Khôi phục lại giá trị đúng của A
A[0, 0] = 0

In [ ]:
# Ví dụ đúng
B2 = A[0:1, 0:3].copy()
B2[0, 0] = -1
print(B2)
""" Kết quả
[[-1  1  2]]
"""

print(A)
""" Kết quả
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
"""

Bạn có thể thay đổi nhiều hơn 1 phần tử trong 1 lệnh như sau

In [ ]:
A1 = A.copy()      # tạo A1 là copy của A để không thay đổi giá trị của A
A1[0:2, 0:3] = -1
print(A1)
""" Kết quả
[[-1 -1 -1  3  4]
 [-1 -1 -1  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
"""

__Checkpoint 2__: Hãy thực hiện những thao tác trên với vector $b$
$$ b = (6.0, 7.0, 8.0, 9.0, 10.0) $$

In [ ]:
# Khởi tạo b

# Truy cập 1 phần tử tồn tại trong b

# Thử truy cập 1 phần tử không tồn tại trong b - quan sát lỗi

# Tạo một vector con của b

# Thay đổi một phần tử trong b và in giá trị mới


# 3. Tính toán trên ma trận

Chúng ta sẽ thực hiện các tính toán trong phần này trên ma trận sau:
$$ A = 
    \begin{bmatrix}
        1 & 2 & 3 \\
        10 & 15 & 20
    \end{bmatrix}
$$

In [ ]:
# code khởi tạo A


* Trong numpy, bạn có thể thực hiện các phép toán tác động lên __toàn bộ__ các phần tử của ma trận y như bạn thao tác trên một phần tử riêng biệt.

    Ví dụ, bạn có thể nhân hoặc chia ma trận cho 1 hằng số. $A * c$ hoặc $A / c$ sẽ nhân (chia) tất cả các phần tử của $A$ cho $c$.

In [ ]:
A = np.array([[1, 2, 3], [10, 15, 20]], dtype=float)
print(A * 3)
print(A / 2)

__Checkpoint 3__: Làm thế nào để thực hiện hàm $sin$, $exp$, và bình phương lên ma trận $A$?

In [ ]:
# sin

# exp

# bình phương


* Những phép toán được thực hiện lên một ma trận con của A một cách tương tự.

In [ ]:
A1 = A.copy()
A1[:, 0] *= 3      # cách viết này tương đương với A1[:, 0] = A1[:, 0] * 3
print(A1)

* Chuyển vị một ma trận thay đổi chiều của ma trận và hoán đổi các phần tử qua đường chéo chính bằng hàm $np.transpose$

$$
    \begin{bmatrix}
        1 & 2 & 3 \\
        10 & 15 & 20
    \end{bmatrix}
 ^T => 
    \begin{bmatrix}
        1 & 10 \\
        2 & 15 \\
        3 & 20
    \end{bmatrix}
$$

In [ ]:
print(np.transpose(A))

* Với 2 ma trận, bạn có thể cộng, trừ hoặc nhân các ma trận với điều kiện số chiều của 2 ma trận phải khớp nhau
    * Phép cộng / trừ yêu cầu số dòng và số cột của 2 ma trận là như nhau
    * Nhân ma trận yêu cầu số cột của $A$ bằng số dòng của $B$.

Hãy khởi tạo ma trận B như dưới đây, và thực hiện phép cộng $A+B$, và phép trừ $A-B$.

$A = \begin{bmatrix}
        1 & 2 & 3 \\
        10 & 15 & 20
    \end{bmatrix}; 
 \ \ \ B = \begin{bmatrix}
        1 & 1 & 1 \\
        2 & 3 & 4
    \end{bmatrix}
$

In [ ]:
# code


In [ ]:
B = np.array([[1, 1, 1], [2, 3, 4]], dtype=float)

print(A + B)
print(A - B)

Làm thế nào để thực hiện phép nhân 2 ma trận này?

$A = \begin{bmatrix}
        1 & 2 & 3 \\
        10 & 15 & 20
    \end{bmatrix}; 
 \ \ \ B = \begin{bmatrix}
        1 & 1 & 1 \\
        2 & 3 & 4
    \end{bmatrix}
$

Nhân ma trận yêu cầu số cột của A bằng số dòng của B!
    
**CẢNH BÁO**: tuyệt đối không sử dụng $*$ để nhân ma trận theo đúng nghĩa nhân ma trận trong toán học. $A*B$ sẽ trả về ma trận mới với mỗi phần tử là tích của 2 phần tử ở vị trí tương ứng trong A và B.

In [ ]:
A*B

Để nhân ma trận, ta sử dụng $np.matmul$.

$A = \begin{bmatrix}
        1 & 2 & 3 \\
        10 & 15 & 20
    \end{bmatrix}; 
 \ \ \ B = \begin{bmatrix}
        1 & 1 & 1 \\
        2 & 3 & 4
    \end{bmatrix}
$

Trong trường hợp này, ta không thể nhân 2 ma trận với nhau. Tuy nhiên nếu ta chuyển vị 1 trong 2 ma trận thì có thể thực hiện phép nhân, ví dụ:

In [ ]:
print(np.matmul(A, np.transpose(B)))

__Checkpoint 4__: nhân ma trận không phải phép toán giao hoán: $np.matmul(A, B)$ không phải là $np.matmul(B, A)$. Hãy đưa ra 2 ma trận $A$ và $B$ làm phản ví dụ. Khẳng định trên có đúng không nếu như $A$ và $B$ đều là ma trận vuông và có cùng số chiều?

In [ ]:
# code


## Hỏi đáp

__Bài tập__: Khởi tạo 1 ma trận kích thước 5 x 7, sau đó đảo ngược giá trị các phần tử trong từng dòng. Bạn có thể tìm ra được cách ngắn gọn nhất không?

In [ ]:
# code
A[:, :] = A[::-1, :-1]    # 0 1 2 4 => 4 3 2 1
a:2:b

In [1]:
import numpy as np

In [4]:
A = np.arange(10).reshape(2, 5)
print(A)
A[:] = A[::-1]
print(A)
A[:, :] = A[::-1, ::-1]
print(A)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[5 6 7 8 9]
 [0 1 2 3 4]]
[[4 3 2 1 0]
 [9 8 7 6 5]]


**Bài tập**: Sử dụng numpy để giải quyết hai bài toán cơ bản sau đây:

* Cho ma trận $A$ và vector $b$, giải hệ phương trình $Ax = b$.
* Cho ma trận $A$ và vector $b$, tìm vector x sao cho giá trị $||Ax - b||_2^2$ là nhỏ nhất.

Giả sử $A$ và $b$ có số chiều khớp nhau và bài toán luôn có lời giải duy nhất.

Để xem các lệnh bạn có thể sử dụng được trong Numpy, hãy truy cập https://docs.scipy.org/doc/numpy/user/. Hai bài tập trên có thể giải quyết được trong không quá 5 dòng lệnh Numpy.

In [ ]:
# code
