# Bài giảng về Đại số tuyến tính
## MaSSP 2017, Computer Science
### Chuẩn bị: Nguyễn Vương Linh, MIT Class of 2017

Bài giảng sau đây giới thiệu một số kiến thức cơ bản về đại số tuyến tính cần thiết để hiểu và thực hiện chương trình <b>Deep Learning</b>.

Bài giảng này bỏ qua một số kiến thức quan trọng (ví dụ như vector riêng), và không đi sâu vào phân tích tính chất của các khái niệm.

Bài giảng này sử dụng thư viện <b>numpy</b> trong Python để thực hiện các ví dụ minh hoạ.

Numpy là một trong những thư viện mã nguồn mở nổi tiếng nhất của Python và được sử dụng rộng rãi trong nhiều chương trình <b>Machine Learning</b> nói chung và <b>Deep Learning</b> nói riêng.

Mục tiêu chính của Numpy là tối ưu và đơn giản hoá các phép toán liên quan đến đại số tuyến tính. Trước khi bắt đầu, hãy cài đặt numpy, và bắt đầu chương trình Python (hoặc notebook) bằng lệnh sau:

In [ ]:
import numpy as np

Lưu ý: khi bạn tải lại notebook này, bạn phải chạy lại lệnh import nói trên.

# 0. Ví dụ cơ bản

Đối tượng cơ bản trong đại số tuyến tính là <b>ma trận</b> và <b>vector</b>. Ví dụ cơ bản sau đây giới thiệu cách thức tương tác với ma trận trong numpy và được thực hiện với ma trận 2 chiều, tuy nhiên các phép toán cơ bản là không thay đổi nếu với số chiều khác.

Các ví dụ chi tiết hơn sẽ được đề cập khi đi sâu vào từng phép toán / trường hợp cụ thể.

Chúng ta bắt đầu với việc khởi tạo một ma trận A và in ra các thông tin cơ bản của A. Khi mới bắt đầu, các bạn hãy trực tiếp thử những lệnh này trên môi trường Python terminal để làm quen với numpy.

Khởi tạo ma trận kích thước 3 x 5, các phần tử từ 0 đến 14, theo thứ tự tăng dần từ trái qua phải và từ trên xuống.

$$ A = 
    \begin{bmatrix}
        0 & 1 & 2 & 3 & 4 \\
        5 & 6 & 7 & 8 & 9 \\
        10 & 11 & 12 & 13 & 14
    \end{bmatrix}
$$

In [ ]:
A = np.arange(15).reshape(3, 5)
print(A)

In các thông tin cơ bản về ma trận A
$$ A = 
    \begin{bmatrix}
        0 & 1 & 2 & 3 & 4 \\
        5 & 6 & 7 & 8 & 9 \\
        10 & 11 & 12 & 13 & 14
    \end{bmatrix}
$$

In [ ]:
print("Shape: {}".format(A.shape))      # In thông tin về các chiều của A

# Để truy cập thông tin của A theo từng chiều, sử dụng chỉ số với A.shape
print(A.shape[0])  
print(A.shape[1])

In [ ]:
""" A
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
"""
print("Dimension: {}".format(A.ndim))   # In số chiều của A

print("Type: {}".format(A.dtype))       # In kiểu dữ liệu của các phần từ trong A

print("Size: {}".format(A.size))        # In số phần tử có trong A

Trong numpy (và Python), các phần tử được đánh số từ 0. Numpy cho phép đọc và thay đổi từng phần tử trong ma trận.

$$ A = 
    \begin{bmatrix}
        0 & 1 & 2 & 3 & 4 \\
        5 & 6 & 7 & 8 & 9 \\
        10 & 11 & 12 & 13 & 14
    \end{bmatrix}
$$

In [ ]:
# Có thể truy cập một phần tử của A bằng lệnh A[i0, i1]
print(A[0, 0])      # Kết quả: 0
print(A[1, 2])      # Kết quả: 7

# numpy cho phép thay đổi thông tin lưu trữ trong ma trận
A[0, 0] = 10
A[1, 1] = -1
print(A)

__Checkpoint 1__: Khởi tạo 1 vector b và thực hiện các phép toán tương tự như ở trên. Sử dụng vector sau đây:
$$ b = (6.0, 7.0, 8.0) $$

In [ ]:
# Khởi tạo b

# In thông tin về các chiều, số chiều, kiểu dữ liệu, số phần tử của b

# Truy cập 1 phần tử tồn tại trong b

# Thử truy cập 1 phần tử không tồn tại trong b - quan sát lỗi

# Thay đổi một phần tử trong b và in giá trị mới


# 1. Khởi tạo ma trận và vector

Chúng ta sẽ khởi tạo một vài ma trận với các định dạng khác nhau để minh hoạ.
$$ A1 = 
    \begin{bmatrix}
        1 & 2 & 3 \\
        6 & 5 & 4
    \end{bmatrix}
$$

Để khởi tạo 1 ma trận với các phần tử được biết trước, sử dụng np.array

In [ ]:
A1 = np.array([[1, 2, 3], [6, 5, 4]])
print(A1)

""" Kết quả:
[[1 2 3]
 [6 5 4]]
"""

$$ A2 = 
    \begin{bmatrix}
        3 & 4 \\
        5 & 6
    \end{bmatrix}
$$

np.array tự động xác định kiểu dữ liệu trong ma trận.

Sử dụng __dtype__ để ép kiểu dữ liệu trong ma trận:

In [ ]:
A2 = np.array([[3, 4], [5, 6]], dtype=float)  # Sử dụng kiểu số thực

print(A2)
""" Kết quả:
[[ 3.  4.]
 [ 5.  6.]]
"""

print(A2.dtype)  # Kết quả: float64

Luôn luôn phải có [] để xác định các phần tử trong ma trận.

Ví dụ sau đây là SAI

In [ ]:
B1 = np.array(1,2,3,4)

## Các ma trận đặc biệt

* Nếu cần khởi tạo ma trận toàn 0, sử dụng __np.zeros__, kèm theo thông tin về kích thước ma trận

In [ ]:
A3 = np.zeros((6, 5), dtype=int)
print(A3)

""" Kết quả:
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
"""

* Tương tự như thế, bạn có thể khởi tạo ma trận toàn 1 bằng __np.ones__:

In [ ]:
A4 = np.ones((4, 2))
print(A4)
""" Kết quả:
[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
"""

* Ma trận đơn vị được khởi tạo bằng __np.eye__

_Lưu ý ma trận đơn vị chỉ có 2 chiều và luôn là ma trận vuông._

In [ ]:
A5 = np.eye(3)
print(A5)

* Cuối cùng, __np.arange__ tạo ra ma trận với các phần tử kế tiếp nhau

__reshape__ được sử dụng để thay đổi kích thước ma trận.

In [ ]:
A6 = np.arange(10, 20).reshape(2, 5)
print(A6)

""" Kết quả:
[[10 11 12 13 14]
 [15 16 17 18 19]]
"""

# 2. Truy cập và thay đổi phần tử trong ma trận

Mặc dù hầu hết các phép toán trong Deep Learning không cần truy cập từng phần tử của ma trận, bạn cũng nên biết một vài cách thức cơ bản để thao tác với từng phần tử trong ma trận.

In [ ]:
# Chúng ta sẽ sử dụng ma trận minh hoạ
A = np.arange(20).reshape(4, 5)
print(A)

""" Kết quả:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
"""

# Như đã nói, bạn có thể truy cập và thay đổi phần tử bằng A[i, j]
print(A[0, 0])
print(A[3, 4])

A[0, 0] = 19
A[3, 4] = 0

print(A)
""" Kết quả:
[[19  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18  0]]
"""

A[0, 0] = 0
A[3, 4] = 19

# Để truy cập cả một dòng hay một cột, sử dụng : thay cho chỉ số không cần thiết
print(A[0, :])  # In ra dòng đầu tiên. Kết quả: [0 1 2 3 4]
print(A[:, 0])  # In ra cột đầu tiên. Kết quả: [ 0  5 10 15]

# Để truy cập một ma trận con, sử dụng a:b để lấy ra phần chỉ số cần thiết.
# Lưu ý: a:b kí hiệu các phần tử từ a đến b - 1.
print(A[2:4, 2:5])
""" Kết quả
[[12 13 14]
 [17 18 19]]
"""

print(A[0:3, :])
""" Kết quả
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
"""

Ma trận / vector con có thể được gán sang biến khác và truy cập / thay đổi tương ứng.

**CẢNH BÁO**: Python không sao chép ma trận trong phép gán =, cho nên LUÔN LUÔN sử dụng copy để tạo ra một ma trận mới và gán = với ma trận đó.

In [ ]:
# Ví dụ SAI
B1 = A[0:1, 0:3]
B1[0, 0] = -1   # Phép toán này thay đổi giá trị tương ứng trong A
print(B1)
""" Kết quả
[[-1  1  2]]
"""

print(A)
""" Kết quả
[[-1  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
"""

# Khôi phục lại giá trị đúng của A
A[0, 0] = 0

# Ví dụ đúng
B2 = A[0:1, 0:3].copy()
B2[0, 0] = -1
print(B2)
""" Kết quả
[[-1  1  2]]
"""

print(A)
""" Kết quả
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
"""

# Bạn có thể thay đổi nhiều hơn 1 phần tử trong 1 lệnh
A1 = A.copy()
A1[0:2, 0:3] = -1
print(A1)
""" Kết quả
[[-1 -1 -1  3  4]
 [-1 -1 -1  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
"""

__Bài tập__: Khởi tạo 1 ma trận kích thước 5 x 7, sau đó đảo ngược giá trị các phần tử trong từng dòng. Có một cách chậm và một cách nhanh; bạn có tìm ra được cách nhanh không?

# 3. Tính toán trên ma trận

Chúng ta khởi tạo 1 ma trận:

In [ ]:
A = np.array([[1, 2, 3], [10, 15, 20]], dtype=float)

# Trong numpy, bạn có thể thực hiện các phép toán tác động lên toàn bộ các phần tử của ma trận.
# y như bạn thao tác trên một phần tử riêng biệt.

# Ví dụ, bạn có thể nhân hoặc chia ma trận cho 1 hằng số.
# A * c hoặc A / c sẽ nhân (chia) tất cả các phần tử của A cho c.
print(A * 3)
print(A / 2)

# Nhân hoặc chia một ma trận con của A được thực hiện tương tự.
A1 = A.copy()
A1[:, 0] *= 3
print(A1)

# Chuyển vị một ma trận thay đổi chiều của ma trận và hoán đổi các phần tử qua đường chéo chính.
# Sử dụng np.transpose để chuyển vị ma trận.
print(np.transpose(A))

# Hãy thử np.exp và np.sin và giải thích xem 2 phép toán này làm gì?
print(np.exp(A))
print(np.sin(A))

# Với 2 ma trận, bạn có thể cộng, trừ hoặc nhân các ma trận với điều kiện số chiều của 2 ma trận phải khớp nhau.
B = np.array([[1, 1, 1], [2, 3, 4]], dtype=float)

# Phép cộng / trừ yêu cầu số dòng và số cột của 2 ma trận là như nhau.
print(A + B)
print(A - B)

# Nhân ma trận yêu cầu số cột của A bằng số dòng của B.
# CẢNH BÁO: tuyệt đối không sử dụng * để nhân ma trận. Chỉ sử dụng * khi bạn hiểu chính xác nó làm gì.
# Thay vào đó, sử dụng np.matmul
print(np.matmul(A, np.transpose(B)))

__Bài tập__: nhân ma trận không phải phép toán giao hoán: np.matmul(A, B) không phải là np.matmul(B, A). Hãy đưa ra 2 ma trận A và B làm phản ví dụ. Khẳng định trên có đúng không nếu như A và B đều là ma trận vuông và có cùng số chiều?

**Bài tập**: Sử dụng numpy để giải quyết hai bài toán cơ bản sau đây:

* Cho ma trận $A$ và vector $b$, giải hệ phương trình $Ax = b$.
* Cho ma trận $A$ và vector $b$, tìm vector x sao cho giá trị $||Ax - b||_2^2$ là nhỏ nhất.

Giả sử $A$ và $b$ có số chiều khớp nhau và bài toán luôn có lời giải duy nhất.

Để xem các lệnh bạn có thể sử dụng được trong Numpy, hãy truy cập https://docs.scipy.org/doc/numpy/user/. Hai bài tập trên có thể giải quyết được trong không quá 5 dòng lệnh Numpy.